package Pj;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

//import L7.testpage3;
//import Pj.Item;

public class First extends javax.swing.JFrame {

	public static String name = "";
	public static String price = "";
	public static String p1 ;
	public static int a = -1;
	public static int d =0;
	public static int total=0;
	
	public static void settotal() {
		total=0;;
	}
	public static void resetD() {
		d=0;;
	}
	public static String getP() {
		return p1;
	}
	
	public static String getNam() {
		return name;
	}
	
	public static String getPrice() {
		return price;
	}
    /**
     * Creates new form first
     */
    public First() {
        initComponents();
        this.setTitle("Menu");
	this.setSize(1100, 650);
	this.setResizable(false);
    }
    
    public static void AddRowToJTable(Object[] dataRow ) {
    	DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
    	model.addRow(dataRow);
    }
    public static void ResetTable() {
    	//DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
    	jTable1.setModel(new DefaultTableModel(null,new String [] {"Item List", "Sweet Level", "Type", "Quantity"}));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        menus = new javax.swing.JTabbedPane();
        signature = new javax.swing.JPanel();
        sign1 = new javax.swing.JLabel();
        sign2 = new javax.swing.JLabel();
        sign3 = new javax.swing.JLabel();
        sign4 = new javax.swing.JLabel();
        sign5 = new javax.swing.JLabel();
        sign6 = new javax.swing.JLabel();
        coffee = new javax.swing.JPanel();
        coffee1 = new javax.swing.JLabel();
        coffee2 = new javax.swing.JLabel();
        coffee3 = new javax.swing.JLabel();
        coffee4 = new javax.swing.JLabel();
        coffee5 = new javax.swing.JLabel();
        coffee6 = new javax.swing.JLabel();
        tea = new javax.swing.JPanel();
        tea1 = new javax.swing.JLabel();
        tea2 = new javax.swing.JLabel();
        tea3 = new javax.swing.JLabel();
        tea4 = new javax.swing.JLabel();
        tea5 = new javax.swing.JLabel();
        tea6 = new javax.swing.JLabel();
        juice = new javax.swing.JPanel();
        juice1 = new javax.swing.JLabel();
        juice2 = new javax.swing.JLabel();
        juice3 = new javax.swing.JLabel();
        juice4 = new javax.swing.JLabel();
        juice5 = new javax.swing.JLabel();
        juice6 = new javax.swing.JLabel();
        cake = new javax.swing.JPanel();
        cake1 = new javax.swing.JLabel();
        cake2 = new javax.swing.JLabel();
        cake3 = new javax.swing.JLabel();
        cake4 = new javax.swing.JLabel();
        cake5 = new javax.swing.JLabel();
        cake6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        orderButton = new javax.swing.JButton();
        billButton = new javax.swing.JButton();
        deleteButton= new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menus.setName(""); // NOI18N
        menus.setPreferredSize(new java.awt.Dimension(1000, 700));

        sign1.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\coffee\\Espresso.png")); // NOI18N
        sign1.setPreferredSize(new java.awt.Dimension(160, 125));
        sign1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        sign1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sign1MousePressed(evt);
            }
        });

        sign2.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\coffee\\Latte.png")); // NOI18N
        sign2.setPreferredSize(new java.awt.Dimension(160, 125));
        sign2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sign2MousePressed(evt);
            }
        });

        sign3.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\tea\\Cocoa.png")); // NOI18N
        sign3.setPreferredSize(new java.awt.Dimension(160, 125));
        sign3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sign3MousePressed(evt);
            }
        });

        sign4.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\juice\\strawberry-juice.png")); // NOI18N
        sign4.setPreferredSize(new java.awt.Dimension(160, 125));
        sign4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sign4MousePressed(evt);
            }
        });

        sign5.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\juice\\orange-juice.png")); // NOI18N
        sign5.setPreferredSize(new java.awt.Dimension(160, 125));
        sign5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sign5MousePressed(evt);
            }
        });

        sign6.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\cake\\rainbow cake.png")); // NOI18N
        sign6.setPreferredSize(new java.awt.Dimension(160, 125));
        sign6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sign6MousePressed(evt);
            }
        });

        javax.swing.GroupLayout signatureLayout = new javax.swing.GroupLayout(signature);
        signature.setLayout(signatureLayout);
        signatureLayout.setHorizontalGroup(
            signatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signatureLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(signatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sign1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sign4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(signatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sign2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sign5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(signatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sign3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sign6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        signatureLayout.setVerticalGroup(
            signatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signatureLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(signatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sign2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sign1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sign3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110)
                .addGroup(signatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sign5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sign4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sign6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(235, Short.MAX_VALUE))
        );

        menus.addTab("Signatures", new javax.swing.ImageIcon("D:\\ProJect\\111\\star.png"), signature); // NOI18N

        coffee1.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\coffee\\Espresso.png")); // NOI18N
        coffee1.setPreferredSize(new java.awt.Dimension(160, 125));
        coffee1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                coffee1MousePressed(evt);
            }
        });

        coffee2.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\coffee\\Americano.png")); // NOI18N
        coffee2.setPreferredSize(new java.awt.Dimension(160, 125));
        coffee2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                coffee2MousePressed(evt);
            }
        });

        coffee3.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\coffee\\Macchiato.png")); // NOI18N
        coffee3.setPreferredSize(new java.awt.Dimension(160, 125));
        coffee3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                coffee3MousePressed(evt);
            }
        });

        coffee4.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\coffee\\Cappuccino.png")); // NOI18N
        coffee4.setPreferredSize(new java.awt.Dimension(160, 125));
        coffee4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                coffee4MousePressed(evt);
            }
        });

        coffee5.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\coffee\\Mocha.png")); // NOI18N
        coffee5.setPreferredSize(new java.awt.Dimension(160, 125));
        coffee5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                coffee5MousePressed(evt);
            }
        });

        coffee6.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\coffee\\Latte.png")); // NOI18N
        coffee6.setPreferredSize(new java.awt.Dimension(160, 125));
        coffee6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                coffee6MousePressed(evt);
            }
        });

        javax.swing.GroupLayout coffeeLayout = new javax.swing.GroupLayout(coffee);
        coffee.setLayout(coffeeLayout);
        coffeeLayout.setHorizontalGroup(
            coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coffeeLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coffee1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coffee4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coffee5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coffee2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(coffee6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coffee3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        coffeeLayout.setVerticalGroup(
            coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coffeeLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coffee2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coffee3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coffee1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addGroup(coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coffee5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coffee6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coffee4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(236, Short.MAX_VALUE))
        );

        menus.addTab("Coffee", new javax.swing.ImageIcon("D:\\ProJect\\111\\coffee.png"), coffee); // NOI18N

        tea1.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\tea\\Cocoa.png")); // NOI18N
        tea1.setPreferredSize(new java.awt.Dimension(160, 125));
        tea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tea1MousePressed(evt);
            }
        });

        tea2.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\tea\\Green-tea.png")); // NOI18N
        tea2.setPreferredSize(new java.awt.Dimension(160, 125));
        tea2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tea2MousePressed(evt);
            }
        });

        tea3.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\tea\\Thai-Milk-Tea.png")); // NOI18N
        tea3.setPreferredSize(new java.awt.Dimension(160, 125));
        tea3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tea3MousePressed(evt);
            }
        });

        tea4.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\tea\\Iced-Pink-Milk.png")); // NOI18N
        tea4.setPreferredSize(new java.awt.Dimension(160, 125));
        tea4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tea4MousePressed(evt);
            }
        });

        tea5.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\tea\\oolong-tea.png")); // NOI18N
        tea5.setPreferredSize(new java.awt.Dimension(160, 125));
        tea5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tea5MousePressed(evt);
            }
        });

        tea6.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\tea\\white-tea.png")); // NOI18N
        tea6.setPreferredSize(new java.awt.Dimension(160, 125));
        tea6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tea6MousePressed(evt);
            }
        });

        javax.swing.GroupLayout teaLayout = new javax.swing.GroupLayout(tea);
        tea.setLayout(teaLayout);
        teaLayout.setHorizontalGroup(
            teaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teaLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(teaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tea4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(teaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tea5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(teaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tea6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tea3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        teaLayout.setVerticalGroup(
            teaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teaLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(teaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tea3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addGroup(teaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tea4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tea5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tea6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(236, Short.MAX_VALUE))
        );

        menus.addTab("Tea", new javax.swing.ImageIcon("D:\\ProJect\\111\\tea-cup.png"), tea); // NOI18N

        juice1.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\juice\\apple-juice.png")); // NOI18N
        juice1.setPreferredSize(new java.awt.Dimension(160, 125));
        juice1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                juice1MousePressed(evt);
            }
        });

        juice2.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\juice\\grape-juice.png")); // NOI18N
        juice2.setPreferredSize(new java.awt.Dimension(160, 125));
        juice2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                juice2MousePressed(evt);
            }
        });

        juice3.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\juice\\orange-juice.png")); // NOI18N
        juice3.setPreferredSize(new java.awt.Dimension(160, 125));
        juice3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                juice3MousePressed(evt);
            }
        });

        juice4.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\juice\\strawberry-juice.png")); // NOI18N
        juice4.setPreferredSize(new java.awt.Dimension(160, 125));
        juice4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                juice4MousePressed(evt);
            }
        });

        juice5.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\juice\\pineapple-juice.png")); // NOI18N
        juice5.setPreferredSize(new java.awt.Dimension(160, 125));
        juice5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                juice5MousePressed(evt);
            }
        });

        juice6.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\juice\\tomato-juice.png")); // NOI18N
        juice6.setPreferredSize(new java.awt.Dimension(160, 125));
        juice6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                juice6MousePressed(evt);
            }
        });

        javax.swing.GroupLayout juiceLayout = new javax.swing.GroupLayout(juice);
        juice.setLayout(juiceLayout);
        juiceLayout.setHorizontalGroup(
            juiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(juiceLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(juiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(juice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(juice4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(juiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(juice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(juice5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(juiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(juice6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(juice3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        juiceLayout.setVerticalGroup(
            juiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(juiceLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(juiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(juice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(juice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(juice3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addGroup(juiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(juice4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(juice5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(juice6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(236, Short.MAX_VALUE))
        );

        menus.addTab("Juice", new javax.swing.ImageIcon("D:\\ProJect\\111\\juice.png"), juice); // NOI18N

        cake1.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\cake\\red velvet cake.png")); // NOI18N
        cake1.setPreferredSize(new java.awt.Dimension(170, 125));
        cake1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cake1MousePressed(evt);
            }
        });

        cake2.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\cake\\cherry cake.png")); // NOI18N
        cake2.setPreferredSize(new java.awt.Dimension(170, 125));
        cake2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cake2MousePressed(evt);
            }
        });

        cake3.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\cake\\strawberry cake.png")); // NOI18N
        cake3.setPreferredSize(new java.awt.Dimension(170, 125));
        cake3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cake3MousePressed(evt);
            }
        });

        cake4.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\cake\\chocolate cake.png")); // NOI18N
        cake4.setPreferredSize(new java.awt.Dimension(170, 125));
        cake4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cake4MousePressed(evt);
            }
        });

        cake5.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\cake\\rainbow cake.png")); // NOI18N
        cake5.setPreferredSize(new java.awt.Dimension(170, 125));
        cake5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cake5MousePressed(evt);
            }
        });

        cake6.setIcon(new javax.swing.ImageIcon("D:\\ProJect\\cake\\cupcake.png")); // NOI18N
        cake6.setPreferredSize(new java.awt.Dimension(170, 125));
        cake6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cake6MousePressed(evt);
            }
        });

        javax.swing.GroupLayout cakeLayout = new javax.swing.GroupLayout(cake);
        cake.setLayout(cakeLayout);
        cakeLayout.setHorizontalGroup(
            cakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cakeLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(cakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cake1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cake4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(cakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cake2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cake5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(cakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cake6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cake3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        cakeLayout.setVerticalGroup(
            cakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cakeLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(cakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cake1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cake2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cake3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addGroup(cakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cake4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cake5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cake6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(236, Short.MAX_VALUE))
        );

        menus.addTab("cake", new javax.swing.ImageIcon("D:\\ProJect\\111\\piece-of-cake.png"), cake); // NOI18N
        
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item List", "Sweet Level", "Type", "Quantity"
            }
        )
        {
            public boolean isCellEditable(int row, int column) {                
                return false;               
            }
        });
        jScrollPane1.setViewportView(jTable1);

        orderButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        orderButton.setText("Order");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	orderButtonActionPerformed(evt);
            }
        });

        billButton.setBackground(new java.awt.Color(204, 204, 204));
        billButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        billButton.setText("BILL");
        billButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	billButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	deleteButtonActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menus, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(deleteButton)
                            .addGap(79, 79, 79)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(billButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(185, 185, 185))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(orderButton)
                        .addComponent(deleteButton))
                    .addGap(36, 36, 36)
                    .addComponent(billButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(menus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
        

        menus.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>
    
    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {  
    	int total=0;
    	if(JFrame.getNum()-d<=0){
            JOptionPane.showMessageDialog(this,"Please select a product!!!","Warning",JOptionPane.PLAIN_MESSAGE);
    	}
    	else {
	    	new testpage3().setVisible(true);
	    	for(int i=d ; i<JFrame.getNum() ; i++) {
		        	testpage3.AddRowToJTable2(new Object[] {
			        		Item.getName(i),
			                Item.getType(i),
			                Item.getPrice(i),
			                Item.getQuantity(i),
			                Item.getPrice(i),
			                Item.getDetail(i),
			    	});
		        	total += Item.getPrice(i);
		        }
	    	System.out.println(total);
	    }
    }    
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) { 
    	DefaultTableModel  model1 = (DefaultTableModel)jTable1.getModel();
    	if(jTable1.getSelectedRowCount()==1) {
    		if(jTable1.getSelectedRow() == 0) {
    			model1.removeRow(0);
    			d+=1;
    		}
    		else {
    			JOptionPane.showMessageDialog(this,"Please select First Row For Delete!");
    		}
    	}
    	else {
    		if(jTable1.getRowCount()==0) {
    			JOptionPane.showMessageDialog(this,"The table is Empty!");
    		}
    		else {
    			JOptionPane.showMessageDialog(this,"Please select First Row For Delete!");
    		}
    	}
    }
    
    private void billButtonActionPerformed(java.awt.event.ActionEvent evt) {         
    	if(JFrame.getNum()-d<=0){
            JOptionPane.showMessageDialog(this,"Please select a product!!!","Warning",JOptionPane.PLAIN_MESSAGE);
    	}
    	else {
    	JOptionPane.showMessageDialog(this,"Please wait the waiter for checking your bill!!!","Information",JOptionPane.PLAIN_MESSAGE);
    	}
    }
    
    private boolean setVisible() {
    	JFrame page2 = new JFrame();
    	page2.setVisible(true);
    	page2.pack();
    	page2.setLocationRelativeTo(null);
    	page2.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		return rootPaneCheckingEnabled;
    }
    //sign1-6 
    private void sign1MousePressed(java.awt.event.MouseEvent evt) {     
    	name = "Espresso";
    	price = "50";
    	p1="D:\\ProJect\\coffee\\Espresso.png";
    	setVisible();       
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
    }                                  
    private void sign2MousePressed(java.awt.event.MouseEvent evt) {  
    	name = "Latte";
    	price = "50";
    	p1="D:\\ProJect\\coffee\\Latte.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
    }                                  

    private void sign3MousePressed(java.awt.event.MouseEvent evt) {     
    	name = "Cocoa";
    	price = "40";
    	p1="D:\\ProJect\\tea\\Cocoa.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
    }                                  

    private void sign4MousePressed(java.awt.event.MouseEvent evt) {   
    	name = "Strawberry Juice";
    	price = "35";
    	p1="D:\\ProJect\\juice\\strawberry-juice.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
        JFrame.hotPanel.setVisible(false);
    }                                  

    private void sign5MousePressed(java.awt.event.MouseEvent evt) {  
    	name = "Orange Juice";
    	price = "35";
    	p1="D:\\ProJect\\juice\\orange-juice.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
        JFrame.hotPanel.setVisible(false);
    }                                  

    private void sign6MousePressed(java.awt.event.MouseEvent evt) {
    	name = "Rainbow Cake";
    	price = "45";
    	p1="D:\\ProJect\\cake\\rainbow cake.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
        JFrame.jPanel1.setVisible(false);
        JFrame.jPanel3.setVisible(false);
    }
    
    //coffee1-6
    private void coffee1MousePressed(java.awt.event.MouseEvent evt) {  
    	name = "Espresso";
    	price = "50";
    	p1="D:\\ProJect\\coffee\\Espresso.png";
        
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
    }                                    

    private void coffee2MousePressed(java.awt.event.MouseEvent evt) { 
    	name = "Americano";
    	price = "50";
    	p1="D:\\ProJect\\coffee\\Americano.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
    }                                    

    private void coffee3MousePressed(java.awt.event.MouseEvent evt) {    
    	name = "Macchiato";
    	price = "50";
    	p1="D:\\ProJect\\coffee\\Macchiato.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
    }                                    

    private void coffee4MousePressed(java.awt.event.MouseEvent evt) {   
    	name = "Cappuccino";
    	price = "50";
    	p1="D:\\ProJect\\coffee\\Cappuccino.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
    }                                    

    private void coffee5MousePressed(java.awt.event.MouseEvent evt) {     
    	name = "Mocha";
    	price = "50";
    	p1="D:\\ProJect\\coffee\\Mocha.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
    }                                    

    private void coffee6MousePressed(java.awt.event.MouseEvent evt) {                                     
    	name = "Latte";
    	price = "50";
    	p1="D:\\ProJect\\coffee\\Latte.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
    }                                    

    //tea1-6
    private void tea1MousePressed(java.awt.event.MouseEvent evt) {    
    	name = "Cocoa";
    	price = "40";
    	p1="D:\\ProJect\\tea\\Cocoa.png";
        setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
    }                                 

    private void tea2MousePressed(java.awt.event.MouseEvent evt) {    
    	name = "Green tea";
    	price = "40";
    	p1="D:\\ProJect\\tea\\Green-tea.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
    }                                 

    private void tea3MousePressed(java.awt.event.MouseEvent evt) { 
    	name = "Thai Milk Tea";
    	price = "40"; 
    	p1="D:\\ProJect\\tea\\Thai-Milk-Tea.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
    }                                 

    private void tea4MousePressed(java.awt.event.MouseEvent evt) { 
    	name = "Iced Pink Milk";
    	price = "40";
    	p1="D:\\ProJect\\tea\\Iced-Pink-Milk.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
    }                                 

    private void tea5MousePressed(java.awt.event.MouseEvent evt) {   
    	name = "Oolong-tea";
    	price = "40";
    	p1="D:\\ProJect\\tea\\oolong-tea.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
    }                                 

    private void tea6MousePressed(java.awt.event.MouseEvent evt) { 
    	name = "White tea";
    	price = "40";
    	p1="D:\\ProJect\\tea\\white-tea.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
    }                                 

    //juice 1-6
    private void juice1MousePressed(java.awt.event.MouseEvent evt) { 
    	name = "Apple Juice";
    	price = "35";
    	p1="D:\\ProJect\\juice\\apple-juice.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
        JFrame.hotPanel.setVisible(false);
    }                                   

    private void juice2MousePressed(java.awt.event.MouseEvent evt) { 
    	name = "Grape Juice";
    	price = "35";
    	p1="D:\\ProJect\\juice\\grape-juice.png";                        
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
        JFrame.hotPanel.setVisible(false);
    }                                   

    private void juice3MousePressed(java.awt.event.MouseEvent evt) { 
    	name = "Orange Juice";
    	price = "35";
    	p1="D:\\ProJect\\juice\\orange-juice.png"; 
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
        JFrame.hotPanel.setVisible(false);
    }                                   

    private void juice4MousePressed(java.awt.event.MouseEvent evt) {  
    	name = "Strawberry Juice";
    	price = "35";
    	p1="D:\\ProJect\\juice\\strawberry-juice.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
        JFrame.hotPanel.setVisible(false);
    }                                   

    private void juice5MousePressed(java.awt.event.MouseEvent evt) {     
    	name = "Pineapple Juice";
    	price = "35";
    	p1="D:\\ProJect\\juice\\pineapple-juice.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
        JFrame.hotPanel.setVisible(false);
    }                                   

    private void juice6MousePressed(java.awt.event.MouseEvent evt) {     
    	name = "Tomato Juice";
    	price = "35";
    	p1="D:\\ProJect\\juice\\tomato-juice.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
        JFrame.hotPanel.setVisible(false);
    }                                   

    //cake 1-6
    private void cake1MousePressed(java.awt.event.MouseEvent evt) {     
    	name = "Red Velvet Cake";
    	price = "45";
    	p1="D:\\ProJect\\cake\\red velvet cake.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
        JFrame.jPanel1.setVisible(false);
        JFrame.jPanel3.setVisible(false); 
    }                                  

    private void cake2MousePressed(java.awt.event.MouseEvent evt) {     
    	name = "Cherry Cake";
    	price = "45";
    	p1="D:\\ProJect\\cake\\cherry cake.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
        JFrame.jPanel1.setVisible(false);
        JFrame.jPanel3.setVisible(false);
    }                                  

    private void cake3MousePressed(java.awt.event.MouseEvent evt) {    
    	name = "Strawberry Cake";
    	price = "45";
    	p1="D:\\ProJect\\cake\\strawberry cake.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
        JFrame.jPanel1.setVisible(false);
        JFrame.jPanel3.setVisible(false);
    }                                  

    private void cake4MousePressed(java.awt.event.MouseEvent evt) {   
    	name = "Chocolate Cake";
    	price = "45";
    	p1="D:\\ProJect\\cake\\chocolate cake.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
        JFrame.jPanel1.setVisible(false);
        JFrame.jPanel3.setVisible(false);
    }                                  

    private void cake5MousePressed(java.awt.event.MouseEvent evt) {   
    	name = "Rainbow Cake";
    	price = "45";
    	p1="D:\\ProJect\\cake\\rainbow cake.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
        JFrame.jPanel1.setVisible(false);
        JFrame.jPanel3.setVisible(false);
    }                                  

    private void cake6MousePressed(java.awt.event.MouseEvent evt) {       
    	name = "Cupcake";
    	price = "45";
    	p1="D:\\ProJect\\cake\\cupcake.png";
    	setVisible();
        JFrame.type1 = "";
        JFrame.sweetLevel = "";
        JFrame.jPanel1.setVisible(false);
        JFrame.jPanel3.setVisible(false);
    }                                  

                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new First().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel cake;
    private javax.swing.JLabel cake1;
    private javax.swing.JLabel cake2;
    private javax.swing.JLabel cake3;
    private javax.swing.JLabel cake4;
    private javax.swing.JLabel cake5;
    private javax.swing.JLabel cake6;
    private javax.swing.JPanel coffee;
    private javax.swing.JLabel coffee1;
    private javax.swing.JLabel coffee2;
    private javax.swing.JLabel coffee3;
    private javax.swing.JLabel coffee4;
    private javax.swing.JLabel coffee5;
    private javax.swing.JLabel coffee6;
    private javax.swing.JButton billButton;
    private javax.swing.JButton orderButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    private javax.swing.JPanel juice;
    private javax.swing.JLabel juice1;
    private javax.swing.JLabel juice2;
    private javax.swing.JLabel juice3;
    private javax.swing.JLabel juice4;
    private javax.swing.JLabel juice5;
    private javax.swing.JLabel juice6;
    private javax.swing.JTabbedPane menus;
    private javax.swing.JLabel sign1;
    private javax.swing.JLabel sign2;
    private javax.swing.JLabel sign3;
    private javax.swing.JLabel sign4;
    private javax.swing.JLabel sign5;
    private javax.swing.JLabel sign6;
    private javax.swing.JPanel signature;
    private javax.swing.JPanel tea;
    private javax.swing.JLabel tea1;
    private javax.swing.JLabel tea2;
    private javax.swing.JLabel tea3;
    private javax.swing.JLabel tea4;
    private javax.swing.JLabel tea5;
    private javax.swing.JLabel tea6;
    // End of variables declaration                   
}