package Pj;

import java.awt.Color;

import javax.swing.JOptionPane;

//import Pj.Item;

public class JFrame extends javax.swing.JFrame {
	/**
	 * Creates new form JFrame
	 */
	public static String price ="";
	public static String type1 = "";
	public static String sweetLevel= "" ;
	public static String level= "" ;
	Item a = new Item();
	public static int i=0;
	
	public static int getNum() {
		return i;
	}
	public static int getDe() {
		return i-=1;
	}
	public static void resetNum() {
		i = 0;
	}
	public static String getPrice() {
		return price;
	}

	public static String getTyp() {
		return type1;
	}

	public static String getSweetLevel() {
		return sweetLevel;
	}
	public static String getLevel() {
		return level;
	}

	public JFrame() {
		initComponents();
		this.setTitle("Option");
		this.setSize(650, 700);
		this.setResizable(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		bgPanel = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		blendedPanel = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		icedPanel = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		hotPanel = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		n100Panel = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		ls50Panel = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		lls25Panel = new javax.swing.JPanel();
		jLabel8 = new javax.swing.JLabel();
		ns0Panel = new javax.swing.JPanel();
		jLabel9 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jLabel12 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setPreferredSize(new java.awt.Dimension(650, 700));

		bgPanel.setBackground(new java.awt.Color(224, 219, 210));
		bgPanel.setPreferredSize(new java.awt.Dimension(650, 700));

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		blendedPanel.setBackground(new java.awt.Color(227, 227, 227));
		blendedPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		blendedPanel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				blendedPanelMousePressed(evt);
			}
		});

		jLabel1.setBackground(new java.awt.Color(255, 255, 255));
		jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
		jLabel1.setText("blended(+10B)");

		javax.swing.GroupLayout blendedPanelLayout = new javax.swing.GroupLayout(blendedPanel);
		blendedPanel.setLayout(blendedPanelLayout);
		blendedPanelLayout
				.setHorizontalGroup(blendedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(blendedPanelLayout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		blendedPanelLayout
				.setVerticalGroup(blendedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blendedPanelLayout.createSequentialGroup()
								.addGap(0, 6, Short.MAX_VALUE).addComponent(jLabel1)));

		icedPanel.setBackground(new java.awt.Color(227, 227, 227));
		icedPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		icedPanel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				icedPanelMousePressed(evt);
			}
		});

		jLabel2.setBackground(new java.awt.Color(255, 255, 255));
		jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
		jLabel2.setText("Iced(+5B)");

		javax.swing.GroupLayout icedPanelLayout = new javax.swing.GroupLayout(icedPanel);
		icedPanel.setLayout(icedPanelLayout);
		icedPanelLayout
				.setHorizontalGroup(icedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								icedPanelLayout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabel2).addContainerGap()));
		icedPanelLayout.setVerticalGroup(icedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						icedPanelLayout.createSequentialGroup().addGap(0, 6, Short.MAX_VALUE).addComponent(jLabel2)));

		hotPanel.setBackground(new java.awt.Color(227, 227, 227));
		hotPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		hotPanel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				hotPanelMousePressed(evt);
			}
		});

		jLabel4.setBackground(new java.awt.Color(255, 255, 255));
		jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
		jLabel4.setText("Hot");

		javax.swing.GroupLayout hotPanelLayout = new javax.swing.GroupLayout(hotPanel);
		hotPanel.setLayout(hotPanelLayout);
		hotPanelLayout.setHorizontalGroup(hotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						hotPanelLayout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel4).addContainerGap()));
		hotPanelLayout.setVerticalGroup(hotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						hotPanelLayout.createSequentialGroup().addGap(0, 6, Short.MAX_VALUE).addComponent(jLabel4)));

		jLabel13.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
		jLabel13.setText("TYPE");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(hotPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(icedPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(blendedPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap())
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(25, 25, 25)
						.addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout.createSequentialGroup().addGap(8, 8, 8)
												.addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(
														hotPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(jPanel1Layout.createSequentialGroup().addGap(50, 50, 50)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(blendedPanel,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(icedPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(0, 0, Short.MAX_VALUE)))
								.addContainerGap()));

		jPanel3.setBackground(new java.awt.Color(255, 255, 255));

		n100Panel.setBackground(new java.awt.Color(227, 227, 227));
		n100Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		n100Panel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				n100PanelMousePressed(evt);
			}
		});

		jLabel5.setBackground(new java.awt.Color(255, 255, 255));
		jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
		jLabel5.setText("Normal(100%)");

		javax.swing.GroupLayout n100PanelLayout = new javax.swing.GroupLayout(n100Panel);
		n100Panel.setLayout(n100PanelLayout);
		n100PanelLayout
				.setHorizontalGroup(n100PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(n100PanelLayout.createSequentialGroup().addContainerGap().addComponent(jLabel5)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		n100PanelLayout.setVerticalGroup(n100PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						n100PanelLayout.createSequentialGroup().addGap(0, 6, Short.MAX_VALUE).addComponent(jLabel5)));

		ls50Panel.setBackground(new java.awt.Color(227, 227, 227));
		ls50Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		ls50Panel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				ls50PanelMousePressed(evt);
			}
		});

		jLabel6.setBackground(new java.awt.Color(255, 255, 255));
		jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
		jLabel6.setText("Less Sweet(50%)");

		javax.swing.GroupLayout ls50PanelLayout = new javax.swing.GroupLayout(ls50Panel);
		ls50Panel.setLayout(ls50PanelLayout);
		ls50PanelLayout
				.setHorizontalGroup(ls50PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(ls50PanelLayout.createSequentialGroup().addContainerGap().addComponent(jLabel6)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		ls50PanelLayout.setVerticalGroup(ls50PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						ls50PanelLayout.createSequentialGroup().addGap(0, 6, Short.MAX_VALUE).addComponent(jLabel6)));

		lls25Panel.setBackground(new java.awt.Color(227, 227, 227));
		lls25Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		lls25Panel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				lls25PanelMousePressed(evt);
			}
		});

		jLabel8.setBackground(new java.awt.Color(255, 255, 255));
		jLabel8.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
		jLabel8.setText("Less Less Sweet(25%)");

		javax.swing.GroupLayout lls25PanelLayout = new javax.swing.GroupLayout(lls25Panel);
		lls25Panel.setLayout(lls25PanelLayout);
		lls25PanelLayout
				.setHorizontalGroup(lls25PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(lls25PanelLayout.createSequentialGroup().addContainerGap().addComponent(jLabel8)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		lls25PanelLayout.setVerticalGroup(
				lls25PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						lls25PanelLayout.createSequentialGroup().addGap(0, 6, Short.MAX_VALUE).addComponent(jLabel8)));

		ns0Panel.setBackground(new java.awt.Color(227, 227, 227));
		ns0Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		ns0Panel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				ns0PanelMousePressed(evt);
			}
		});

		jLabel9.setBackground(new java.awt.Color(255, 255, 255));
		jLabel9.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
		jLabel9.setText("Not Sweet(0%)");

		javax.swing.GroupLayout ns0PanelLayout = new javax.swing.GroupLayout(ns0Panel);
		ns0Panel.setLayout(ns0PanelLayout);
		ns0PanelLayout.setHorizontalGroup(ns0PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(ns0PanelLayout.createSequentialGroup().addContainerGap().addComponent(jLabel9)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		ns0PanelLayout.setVerticalGroup(ns0PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						ns0PanelLayout.createSequentialGroup().addGap(0, 6, Short.MAX_VALUE).addComponent(jLabel9)));

		jLabel14.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
		jLabel14.setText("SWEET LEVEL");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap(7, Short.MAX_VALUE)
						.addComponent(ns0Panel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(lls25Panel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(ls50Panel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(n100Panel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap())
				.addGroup(jPanel3Layout.createSequentialGroup().addGap(25, 25, 25)
						.addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addGap(8, 8, 8)
						.addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(ns0Panel, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(ls50Panel, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(n100Panel, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lls25Panel, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jButton1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
		jButton1.setText("Cancel");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

		jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		//jLabel10.setText("Picture");
		jLabel10.setIcon(new javax.swing.ImageIcon(First.getP()));
		jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

		jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel11.setText(First.getPrice()+" Bath");//price
                jLabel11.setFont(new java.awt.Font("Bahnschrift", 1, 27));
		//jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

		jButton2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
		jButton2.setText("Move to cart and Continue");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

		jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel12.setText(First.getNam());//name
                jLabel12.setFont(new java.awt.Font("Bahnschrift", 1, 27));
		//jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

		javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
		bgPanel.setLayout(bgPanelLayout);
		bgPanelLayout.setHorizontalGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(bgPanelLayout.createSequentialGroup().addGroup(bgPanelLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(bgPanelLayout.createSequentialGroup().addGap(40, 40, 40)
								.addGroup(bgPanelLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(bgPanelLayout.createSequentialGroup()
												.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18).addComponent(jButton2,
														javax.swing.GroupLayout.PREFERRED_SIZE, 210,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addGroup(bgPanelLayout.createSequentialGroup().addGap(175, 175, 175)
								.addGroup(bgPanelLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 307,
												Short.MAX_VALUE)
										.addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
						.addContainerGap(60, Short.MAX_VALUE)));
		bgPanelLayout.setVerticalGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
						.addGap(50, 50, 50)
						.addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 270,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
								.addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(23, 23, 23)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	void setColor(javax.swing.JPanel panel) {
		panel.setBackground(new Color(255, 204, 153));
	}

	void resetColor(javax.swing.JPanel panel) {
		panel.setBackground(new Color(227, 227, 227));
	}

	private void icedPanelMousePressed(java.awt.event.MouseEvent evt) {
		setColor(icedPanel);
		resetColor(blendedPanel);
		resetColor(hotPanel);
		
		type1 = "Iced";
		
		int a=Integer.parseInt(First.getPrice());
		a+=5;
		jLabel11.setText(String.valueOf(a)+" Bath");
		price = String.valueOf(a);
		a=0;
	}

	private void hotPanelMousePressed(java.awt.event.MouseEvent evt) {
		setColor(hotPanel);
		resetColor(blendedPanel);
		resetColor(icedPanel);
		
		type1 = "Hot";
		
		jLabel11.setText(First.getPrice()+" Bath");
		
	}

	private void blendedPanelMousePressed(java.awt.event.MouseEvent evt) {
		setColor(blendedPanel);
		resetColor(icedPanel);
		resetColor(hotPanel);
		
		type1 = "Blended";
		
		int a=Integer.parseInt(First.getPrice());
		a+=10;
		jLabel11.setText(String.valueOf(a)+" Bath");
		price = String.valueOf(a);
		a=0;
	}

	private void n100PanelMousePressed(java.awt.event.MouseEvent evt) {
		setColor(n100Panel);
		resetColor(ls50Panel);
		resetColor(lls25Panel);
		resetColor(ns0Panel);
		
		sweetLevel = "Normal(100%)";
		level = "100%";
	}

	private void ls50PanelMousePressed(java.awt.event.MouseEvent evt) {
		setColor(ls50Panel);
		resetColor(n100Panel);
		resetColor(lls25Panel);
		resetColor(ns0Panel);
		
		sweetLevel = "Less Sweet(50%)";
		level = "50%";
	}

	private void lls25PanelMousePressed(java.awt.event.MouseEvent evt) {
		setColor(lls25Panel);
		resetColor(n100Panel);
		resetColor(ls50Panel);
		resetColor(ns0Panel);
		
		sweetLevel = "Less Less Sweet(25%)";
		level = "25%";
	}

	private void ns0PanelMousePressed(java.awt.event.MouseEvent evt) {
		setColor(ns0Panel);
		resetColor(n100Panel);
		resetColor(ls50Panel);
		resetColor(lls25Panel);
		
		sweetLevel = "Not Sweet(0%)";
		level = "0%";
		
	}
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		
		a.setName(jLabel12.getText(),i);
		a.setType(getTyp(), i);
		a.setPrice(Integer.parseInt(First.getPrice()), i);
		a.setQuantity(1, i);
		a.setDetail(getSweetLevel(), i);
                
        if(jPanel1.isVisible()){   
            if("".equals(type1) && "".equals(sweetLevel)){
                JOptionPane.showMessageDialog(this,"Please select type and Sweet level!!!","Warning",JOptionPane.WARNING_MESSAGE);

            }
             else if("".equals(type1)){
                JOptionPane.showMessageDialog(this,"Please select type!!!","Warning",JOptionPane.WARNING_MESSAGE);

            }
            else if("".equals(sweetLevel)){
                JOptionPane.showMessageDialog(this,"Please select sweet level!!!","Warning",JOptionPane.WARNING_MESSAGE);

            }
            else{
                First.AddRowToJTable(new Object[] {
                           a.getName(i),
                            getLevel(),
                        a.getType(i),
                        ("1"),
                });
                    type1 = "";
                    sweetLevel = "";
                    level = "";
                    i++;
                this.setVisible(false);
            }
        }
          else{
                First.AddRowToJTable(new Object[] {
                           a.getName(i),
                            getLevel(),
                        a.getType(i),
                        ("1"),
                });
                    type1 = "";
                    sweetLevel = "";
                    i++;
                this.setVisible(false);
            }
        
    	}
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		//cancel button
		type1 = "";
		sweetLevel = "";
		price = "0";
		level = "";
		this.setVisible(false);
    }

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new JFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JPanel bgPanel;
	private javax.swing.JPanel blendedPanel;
	protected static javax.swing.JPanel hotPanel;
	private javax.swing.JPanel icedPanel;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	protected static javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	protected static javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel2;
	protected static javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel lls25Panel;
	private javax.swing.JPanel ls50Panel;
	private javax.swing.JPanel n100Panel;
	private javax.swing.JPanel ns0Panel;
	// End of variables declaration
}